version: '3'

services:
  web:
    build: .
    ports:
      - "7860:7860"
    environment:
      - FLASK_ENV=development
      - MAIL_SERVER=smtp.example.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=your_email@example.com
      - MAIL_PASSWORD=your_password